# Generated by Django 4.2.5 on 2023-10-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_examstypes_examstype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamsType',
            new_name='ExamsTypes',
        ),
    ]
