# Generated by Django 4.2.5 on 2023-10-04 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_rename_examstype_examstypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Under Analysis'), ('F', 'Finished')], max_length=2)),
                ('result', models.FileField(blank=True, null=True, upload_to='results')),
                ('pass_required', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=6, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.examstypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('exams', models.ManyToManyField(to='exams.examrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
