# Generated by Django 4.2.5 on 2023-10-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_medicalaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalaccess',
            old_name='date_final_exams',
            new_name='final_exam_date',
        ),
        migrations.RenameField(
            model_name='medicalaccess',
            old_name='date_start_exams',
            new_name='start_exam_date',
        ),
    ]
